use std::error::Error;

mod data_handling;

fn main() -> Result<(), Box<dyn Error>> {
    
    Ok(())
}
